name: build

on:
  push: {branches: main}
  pull_request: {branches: main}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    env:
      IMAGE_NAME: sample-app
    name: Build and Run
    steps:
      - uses: actions/checkout@v2
      - name: check environment
        run: echo ${{ env.IMAGE_NAME }}
      - name: check build tools and folder structure
        run: |
          ls
          pwd
          cmake --version
          make --version
      - name: build using g++
        run: |
          g++ -I ./include -c ./src/src.cpp 
          g++ -I ./include -c ./src/main.cpp 
          g++ src.o main.o -o hello.out
          ./hello.out
      - name: build using clang++
        run: |
          clang++ -I ./include -c ./src/src.cpp
          clang++ -I ./include -c ./src/main.cpp
          clang++ src.cpp main.cpp -o hello.out
          ./hello.out
      - name: build using make
        run: |
          make
          ./output.out
